Subscribe to invalid id error
opencve/opencve pull request #126
Opened 2021-07-19 20:02 UTC by zachw66

In reference to #121 :
This change to the subscriptions controller verifies that the id being passed into the subscriptions POST request is not an invalid ID. It does this by first checking if the ID is passed in is a valid uuid, but then also verifies that it exists within the database if it is a valid uuid. If there is any problem with the id that is passed in, a 400 error is thrown and a JSON response is sent that the id does not exist.

2021-07-20 06:01 UTC, ncrocfer requested changes

2021-07-20 06:01 UTC, ncrocfer commented on tests/controllers/test_subscriptions.py
> +        assert b'"message":"vendor invalid_id does not exist"' in response.data
You now use `jsonify`, so I thing you can now assert a dict comparison.

2021-07-20 06:01 UTC, ncrocfer commented on tests/controllers/test_subscriptions.py
> +        assert b'"message":"product invalid_id does not exist"' in response.data
Same comment as before, please use `response.data["message"] == "..."`

2021-07-20 17:03 UTC, zachw66 commented
Hi @ncrocfer,

Thank you for the feedback on the code. I have made a change to only use one query and use the JSON that is returned in the response. I also wanted to catch the HTTPException that sends a 404 status code to throw the 400 error with the proper error message instead. If there are other changes you would like me to make, please let me know. Thank you for reviewing my code and allowing me to contribute to the project 🙂

2021-07-21 07:14 UTC, ncrocfer commented
I'm sorry @zachw66 but I don't understand why you use `HTTPException` (maybe it's me ^^). Can you just do this ?

```python
# Vendor
if request.form["obj"] == "vendor":
    if not is_valid_uuid(request.form["id"]):
        return _bad_request(request.form["obj"], request.form["id"])

    vendor = Vendor.query.get(request.form["id"])
    if not vendor:
        return _bad_request(request.form["obj"], request.form["id"])
```

2021-07-21 14:37 UTC, zachw66 commented
> I'm sorry @zachw66 but I don't understand why you use `HTTPException` (maybe it's me ^^). Can you just do this ?
> 
> ```python
> # Vendor
> if request.form["obj"] == "vendor":
>     if not is_valid_uuid(request.form["id"]):
>         return _bad_request(request.form["obj"], request.form["id"])
> 
>     vendor = Vendor.query.get(request.form["id"])
>     if not vendor:
>         return _bad_request(request.form["obj"], request.form["id"])
> ```

Hi @ncrocfer,

I think it is important to not only catch something like "invalid_id", but also IDs that look valid (follow the valid UUID4 format) but don't actually exist within the database. Currently, it would throw an HTTPException and return a 404 not found, but I would like to catch that and return the proper error message with all the information. While the above code is definitely more simple and catches the obvious case of an invalid id, it is important to catch all possibilities of the invalid id here and be consistent with the return status codes and messages.

2021-07-21 19:52 UTC, ncrocfer commented
I totally agree with you, and I'm sorry but my code checks both cases (UID validation + vendor existence), trust me the `HTTPException` is useless :)

You have to know that in SQLalchemy `Vendor.query.get()` returns `None` if the object doesn't exist, and not a 404 error as you say:

```python
>>> from opencve.models.vendors import Vendor
>>> vendor = Vendor.query.get("3060efc9-9199-4954-bf08-972a0723e598")
>>> if vendor:
...     print(vendor)
...
<Vendor ssh>
>>> vendor = Vendor.query.get("3060efc9-9199-4954-bf08-972a0723abcd")
>>> if vendor:
...     print(vendor)
... else:
...     print("no exists")
...
no exists
```

Because I already check its validity before (with `is_valid_uuid()`), and because I check its existence (`if not vendor`), no need to use `HTTPException` in the code.

When I read your code I think you're confusing `opencve.models.vendors.Vendor` and `opencve.controllers.vendors.VendorController`. Indeed the last one raises a 404 error if vendor doesn't exist, but not the first one.

How can I guess it ? Because you import `opencve.controllers.vendors.VendorController` in the first lines of your PR and you never use it later ^^ I didn't ask to fix it because this PR is already taking too long :p

2021-07-21 20:02 UTC, ncrocfer requested changes

2021-07-21 20:02 UTC, ncrocfer commented on opencve/controllers/subscriptions.py
> +                return _bad_request(request.form["obj"], request.form["id"])
```suggestion
        vendor = Vendor.query.get(request.form["id"])
        if not vendor:
            return _bad_request(request.form["obj"], request.form["id"])
```
```

2021-07-21 20:02 UTC, ncrocfer commented on opencve/controllers/subscriptions.py
> +                return _bad_request(request.form["obj"], request.form["id"])
```suggestion
        product = Product.query.get(request.form["id"])
        if not product:
            return _bad_request(request.form["obj"], request.form["id"])
```

2021-07-21 20:05 UTC, zachw66 commented
> I totally agree with you, and I'm sorry but my code checks both cases (UID validation + vendor existence), trust me the `HTTPException` is useless :)
> 
> You have to know that in SQLalchemy `Vendor.query.get()` returns `None` if the object doesn't exist, and not a 404 error as you say:
> 
> ```python
> >>> from opencve.models.vendors import Vendor
> >>> vendor = Vendor.query.get("3060efc9-9199-4954-bf08-972a0723e598")
> >>> if vendor:
> ...     print(vendor)
> ...
> <Vendor ssh>
> >>> vendor = Vendor.query.get("3060efc9-9199-4954-bf08-972a0723abcd")
> >>> if vendor:
> ...     print(vendor)
> ... else:
> ...     print("no exists")
> ...
> no exists
> ```
> 
> Because I already check its validity before (with `is_valid_uuid()`), and because I check its existence (`if not vendor`), no need to use `HTTPException` in the code.
> 
> When I read your code I think you're confusing `opencve.models.vendors.Vendor` and `opencve.controllers.vendors.VendorController`. Indeed the last one raises a 404 error if vendor doesn't exist, but not the first one.
> 
> How can I guess it ? Because you import `opencve.controllers.vendors.VendorController` in the first lines of your PR and you never use it later ^^ I didn't ask to fix it because this PR is already taking too long :p

Ah, yes you are correct that I was mistaken and had initially used VendorController which gives the 404 error. Thank you for explaining the SQLAlchemy query returning None to me; this is my first time using it. I will add your code and remove the unnecessary VendorController import. My apologies for the confusion.

2021-07-22 07:06 UTC, ncrocfer approved these changes
Thanks for this PR :)

2021-07-22 07:06 UTC, merged

2021-07-22 18:04 UTC, zachw66 commented
> Thanks for this PR :)

Thank you for being patient with me in getting it done!