Added and modified search filters in Admin menu
opencve/opencve pull request #181
Opened 2022-02-28 23:01 UTC by gitmopp

The following small enhacement makes searching in the admin interface much easier.
CveModelView: Added column_filters for updated_at
EventModelView: Added Added column_filters and column_searchable_list support  type, created_at
VendorModelView & ProductModelView: Added column_filters and column_searchable_list support for name

2022-03-01 09:04 UTC, gitmopp reviewed
Enabled Export CSV
I merged it with my first Pull Request.

2022-03-05 09:09 UTC, ncrocfer requested changes
Hi @gitmopp ,

First of all thanks for this PR ! I will approve the first commit, but I will not approve the second one (and unfortunately you created one PR for 2 changes, so I can not merge it).

I tried to export the list of Events or CVEs in my local instance of OpenCVE and it failed, the list is too big so Gunicorn timed out (it worked for Vendors and Products). Maybe it works on small instance of OpenCVE, but with 200k events it's not possible:
<img width="599" alt="image" src="https://user-images.githubusercontent.com/1552526/156876655-2e284a2e-f55f-46a2-9e81-455041673fc1.png">


So please can you remove this 2nd commit concerning the CSV export? I will approve and merge the first one.

Thanks again for your PR !

2022-03-06 08:58 UTC, gitmopp commented
I removed can_export

2022-03-07 08:26 UTC, ncrocfer approved these changes

2022-03-07 08:27 UTC, merged