New API Endpoint (Subscriptions)
opencve/opencve pull request #99
Opened 2021-05-04 11:13 UTC by ChriZzn

Hi, i've added a new Endpoint, to get the current_user Subscriptions (by Vendor or by Product).

Would be nice if you merge this...i will need this in some future projects :)

Regards Christoph

2021-05-10 07:36 UTC, ncrocfer requested changes
Details given in a previous comment (squash commits, run black, change route names) :)

2021-05-11 09:13 UTC, ChriZzn commented
hi @ncrocfer,

ive updates as told...but to be honest i cant find the sqash function... :D 

I hope to Code fits now?

Regards Christoph

2021-05-14 06:48 UTC, ncrocfer approved these changes

2021-05-14 22:31 UTC, ldurnez approved these changes

2021-05-15 07:56 UTC, merged